version: '2'
services:
  #######################################
  # Application
  #######################################
  app:
    build:
      context: ./.docker/app
    depends_on:
      - db
      - mail
    links:
      - db
      - mail
    volumes:
      - ./bedrock:/var/www/html/
    environment:
      - DB_NAME=wp
      - DB_USER=wp
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PREFIX=wp_
      - WP_ENV=development
      - WP_HOME=http://$PROJECT_NAME.docker
      - WP_SITEURL=http://$PROJECT_NAME.docker/wp

  #######################################
  # Webserver
  #######################################
  web:
    build:
      context: ./.docker/web
    depends_on:
      - app
    links:
      - app
    volumes_from:
      - app
    environment:
      - VIRTUAL_HOST=$PROJECT_NAME.docker
      - VIRTUAL_PORT=80
    # substitute hostname to nginx conf; syntax from here: https://github.com/docker-library/docs/issues/496#issuecomment-203003827
    command: /bin/sh -c "envsubst '$$VIRTUAL_HOST' < /etc/nginx/site.conf.template > /etc/nginx/site.conf && nginx -g 'daemon off;'"
    ports:
      - 8000:3000
    expose:
      - 80

  #######################################
  # Node
  #######################################
  node:
    restart: 'no'
    image: node:slim
    depends_on:
      - web
    volumes_from:
      - web
    working_dir: /var/www/html/web/app/themes/$PROJECT_NAME
    build:
      context: ./.docker/node
      args:
        - SITE_VERSION=0.0.1
    ports:
      - 3000:3000
      - 3001:3001

  #######################################
  # Database
  #######################################
  # Enable port mapping to access the database via
  # host: localhost
  # port: 3306
  #######################################
  db:
    image: mariadb
#    ports:
#      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wp
      - MYSQL_USER=wp
      - MYSQL_PASSWORD=password

  #######################################
  # phpMyAdmin
  #######################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    links:
      - db
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=phpmyadmin.$PROJECT_NAME.docker
      - PMA_ABSOLUTE_URI=http://phpmyadmin.$PROJECT_NAME.docker/
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=wp
      - PMA_PASSWORD=password

  #######################################
  # Mailhog
  #######################################
  mail:
    image: mailhog/mailhog
    environment:
      - VIRTUAL_PORT=8025
      - VIRTUAL_HOST=mail.$PROJECT_NAME.docker

  #######################################
  # Composer
  #######################################
  composer:
    image: composer
    volumes:
      - ./bedrock:/app

  #######################################
  # CI-Test
  #######################################
  test:
    build:
      context: ./.docker/web
    depends_on:
      - web
      - phpmyadmin
      - mail
    links:
      - web:$PROJECT_NAME.docker
      - phpmyadmin:phpmyadmin.$PROJECT_NAME.docker
      - mail:mail.$PROJECT_NAME.docker
